extra_skills = [
    'python',
    'java',
    'c',
    'c++',
    'sql',
    'mysql',
    'postgresql',
    'mongodb',
    'pandas',
    'numpy',
    'matplotlib',
    'seaborn',
    'plotly',
    'scikit-learn',
    'tensorflow',
    'pytorch',
    'streamlit',
    'flask',
    'fastapi',
    'power bi',
    'tableau',
    'excel',
    'machine learning',
    'deep learning',
    'nlp',
    'computer vision',
    'data science',
    'data analysis',
    'data analytics',
    'feature engineering',
    'git',
    'github',
    'api',
    'web scraping'
]
skill_aliases = {
    "machine learning": ["ml"],
    "artificial intelligence": ["ai"],
    "natural language processing": ["nlp"],
    "power bi": ["powerbi"],
    "scikit-learn": ["sklearn", "scikit learn"]
}